// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import Hero from './Hero/index.svelte';
import TechList from './TechList/index.svelte';

export const components = {
	biography: Biography,
	hero: Hero,
	tech_list: TechList
};
