// Code generated by Slice Machine. DO NOT EDIT.

import Biography from './Biography/index.svelte';
import Contentindex from './Contentindex/index.svelte';
import Experience from './Experience/index.svelte';
import Hero from './Hero/index.svelte';
import ImageBlock from './ImageBlock/index.svelte';
import RichText1 from './RichText1/index.svelte';
import TechList from './TechList/index.svelte';

export const components = {
	biography: Biography,
	contentindex: Contentindex,
	experience: Experience,
	hero: Hero,
	image_block: ImageBlock,
	rich_text: RichText1,
	tech_list: TechList
};
